#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	x-terminal-emulator

elif [[ "$1" == "--ff" ]]; then
#	x-www-browser
brave
elif [[ "$1" == "--fm" ]]; then
#	xdg-mime query default inode/directory | awk -F"[.]" '{print tolower ($3)}' | sh
	thunar
elif [[ "$1" == "--ap" ]]; then
	rofi -show drun -theme ~/.config/rofi/global/rofi.rasi

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--tg" ]]; then
	telegram-desktop &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--ml" ]]; then
	firefox --new-tab "https://mail.google.com"

elif [[ "$1" == "--pow" ]]; then
	xfce4-power-manager-settings &

elif [[ "$1" == "--nm" ]]; then
	networkmanager_dmenu

fi
