[colors.bright]
black = "#928374"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e3a84e"

[colors.normal]
black = "#665c54"
blue = "#7daea3"
cyan = "#89b482"
green = "#a9b665"
magenta = "#d3869b"
red = "#ea6962"
white = "#dfbf8e"
yellow = "#e78a4e"

[colors.primary]
background = "#282828"
foreground = "#dfbf8e"
